version: "3.9"

services:
  node_app_book:
    container_name: node_app_book
    build: .
    image: joseph/node_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_dbBook
      - PG_USER=joseph
      - PG_PASSWORD=12345
      - PG_HOST=node_dbBook
    depends_on:
      - node_dbBook

  node_dbBook:
    container_name: node_dbBook
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_dbBook
      - POSTGRES_USER=joseph
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}